name: '@tjsr/action-npm-outdated'
description: Check for outdated npm packages
author: Tim Rowe <tim@tjsr.id.au>
inputs:
  dependency:
    description: 'Dependency to check'
    required: true
  project:
    description: 'The target project name that must be the owner of the package. This is usually the directory name the package.json file resides under, not the name field in package.json'
    required: false
  failOnNoNewVersion:
    description: 'Whether the build should fail with an exit code if no new version is available for the specified package'
    required: false
    default: false
  skipNpmCiExecute:
    description: 'Whether to skip the npm ci command execution being called implicitly'
    required: false
    default: true
  projectPath:
    description: 'The path to the project to run npm-related scripts within'
    required: false
outputs:
  current:
    description: 'The current version used by the package'
    value: ${{ steps.action-npm-outdated.outputs.current }}
  hasNewVersion:
    description: 'Whether or not there is a new version'
    value: ${{ steps.action-npm-outdated.outputs.hasNewVersion }}
  latest:
    description: 'The latest version available'
    value: ${{ steps.action-npm-outdated.outputs.latest }}
  wanted:
    description: 'The version wanted by the package'
    value: ${{ steps.action-npm-outdated.outputs.wanted }}
  dependent:
    description: 'The dependent package name - should be the same as the project input value'
    value: ${{ steps.action-npm-outdated.outputs.dependent }}

runs:
  using: 'composite'
  steps:
  # - name: npm outdated all check
  #   shell: bash
  #   run: |
  #     npm outdated --json --all || true
  - name: npm outdated check
    shell: bash
    run: |
      npm outdated --verbose --json || true
  # - name: npm outdated dep only check
  #   shell: bash
  #   run: |
  #     npm outdated --verbose --json ${{ inputs.dependency }} || true
  - run: . $GITHUB_ACTION_PATH/outdated.sh
    env:
      INPUT_DEPENDENCY: ${{ inputs.dependency }}
      INPUT_PROJECT: ${{ inputs.project }}
      INPUT_FAIL_ON_NO_NEW_VERSION: ${{ inputs.failOnNoNewVersion }}
      INPUT_SKIP_NPM_CI_EXECUTE: ${{ inputs.skipNpmCiExecute }}
      INPUT_PROJECT_PATH: ${{ inputs.projectPath }}
    shell: bash
    id: action-npm-outdated
    name: Run action-npm-outdated
